groups:
  - name: example_alerts
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance) < 0.2  # More than 80% CPU usage
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) < 0.1  # Less than 10% memory available
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Less than 10% memory available for more than 5 minutes."

      - alert: HighDiskUsage
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1  # Less than 10% disk space available
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Less than 10% disk space available for more than 5 minutes."

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (instance) / sum(rate(http_requests_total[5m])) by (instance) > 0.05  # More than 5% error rate
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "Error rate is above 5% for more than 5 minutes."

      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, instance)) > 0.5  # 95th percentile response time > 500ms
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Slow response time on {{ $labels.instance }}"
          description: "95th percentile response time is above 500ms for more than 5 minutes."
