rule_files:
  - 'alert.rules.yml'  # Path to your alert rules file

global:
  scrape_interval: 15s  # How often to scrape metrics (default is 1m)

scrape_configs:
  - job_name: 'my_application'  # Job name for your application
    static_configs:
      - targets: ['localhost:8081']  # Replace with your application endpoint

  - job_name: 'node_exporter'  # Job name for Node Exporter
    static_configs:
      - targets: ['localhost:9100']  # Node Exporter target

##  ./prometheus --config.file=prometheus.yml (command to run)

